### ISSUE TITLE
WARNING: Version 2.4.4

### ISSUE THREAD

**Issue by DDougster** [wpexpertsio/Post-SMTP#71]
I just tried this version and it has the ISSUE with sending a malformed email that is completely unreadable. Do not use this version if you want your mail to be read correctly on the other side.

**Comment by DDougster** [comment]
Here is what I received when it sent a test email:

MIME-Version: 1.0

Content-Type: multipart/alternative;
boundary="=_887410ab3cc79a4f83ec72e21564b297"

From: Monical's Pizza <[monicals@monicals.com](mailto:monicals@monicals.com)>

To: [DSDavis@monicals.com](mailto:DSDavis@monicals.com)

Message-Id: <[56c1c8db3571a7ff24061d17940d200a@monicals.biz](mailto:56c1c8db3571a7ff24061d17940d200a@monicals.biz)>

Subject: Postman SMTP Test ([www.monicals.biz](http://www.monicals.biz/))

Date: Thu, 09 Mar 2023 14:41:37 +0000


--=_887410ab3cc79a4f83ec72e21564b297
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hello!=0D=0DSent by Postman 2.4.4 - https://wordpress.org/plugins/post-s=
mtp/=0D=0D

--=_887410ab3cc79a4f83ec72e21564b297
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN " "http://w/=
ww.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">=0D<html xmlns=3D"http:=
//[www.w3.org/1999/xhtml](http://www.w3.org/1999/xhtml)">=0D<head>=0D<meta http-equiv=3D"Content-Type" c=
ontent=3D"text/html; charset=3Dutf-8" />=0D<style type=3D"text/css" medi=
a=3D"all">=0D.wporg-notification .im {=0D=09color: #888;=0D} /* undo a G=
Mail-inserted style */=0D</style>=0D</head>=0D<body class=3D"wporg-notif=
ication">=0D=09<div style=3D"background: #e8f6fe; font-family: &amp; quo=
t; Helvetica Neue&amp;quot; , Helvetica ,Arial,sans-serif; font-size: 14=
px; color: #666; text-align: center; margin: 0; padding: 0">=0D=09=09<ta=
ble border=3D"0" cellspacing=3D"0" cellpadding=3D"0" bgcolor=3D"#e8f6fe"=
=09style=3D"background: #e8f6fe; width: 100%;">=0D=09=09=09<tbody>=0D=09=
=09=09=09<tr>=0D=09=09=09=09=09<td>=0D=09=09=09=09=09=09<table border=3D=
"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"center" style=3D"paddin=
g: 0px; width: 100%;"">=0D=09=09=09=09=09=09=09<tbody>=0D=09=09=09=09=09=
=09=09=09<tr>=0D=09=09=09=09=09=09=09=09=09<td>=0D=09=09=09=09=09=09=09=
=09=09=09<div style=3D"max-width: 600px; height: 400px; margin: 0 auto;=
overflow: hidden;background-image:url('https://ps.w.org/postman-smtp/as=
sets/email/poofytoo.png');background-repeat: no-repeat;">=0D=09=09=09=09=
=09=09=09=09=09=09=09<div style=3D"margin:50px 0 0 300px; width:300px; f=
ont-size:2em;">Hello! - &#20320;&#22909; - Bonjour! - &#2344;&#2350;&#23=
60;&#2381;&#2340;&#2375; - =C2=A1Hola! - Ol&#225; - &#1055;&#1088;&#1080=
;&#1074;&#1077;&#1090;! - &#20170;&#26085;&#12399;</div>=0D=09=09=09=09=
=09=09=09=09=09=09=09<div style=3D"text-align:right;font-size: 1.4em; co=
lor:black;margin:150px 0 0 200px;">Sent by Postman 2.4.4=0D=09=09=09=09=
=09=09=09=09=09=09=09=09<br/>=0D=09=09=09=09=09=09=09=09=09=09=09</div>=
=0D=09=09=09=09=09=09=09=09=09=09</div>=0D=09=09=09=09=09=09=09=09=09</t=
d>=0D=09=09=09=09=09=09=09=09</tr>=0D=09=09=09=09=09=09=09</tbody>=0D=09=
=09=09=09=09=09</table>=0D=09=09=09=09=09=09<br><span style=3D"font-size=
:0.9em;color:#94c0dc;">Image source: <a style=3D"color:#94c0dc" href=3D"=
http://poofytoo.com/ ">poofytoo.com</a> - Used with permission</span>=0D=
=09=09=09=09=09</td>=0D=09=09=09=09</tr>=0D=09=09=09</tbody>=0D=09=09</t=
able>=0D</body>=0D</html>

--=_887410ab3cc79a4f83ec72e21564b297--

**Comment by smusmanobjects** [comment]
Hi there,

I hope you are doing well, could you please download [this](https://github.com/wpexpertsio/Post-SMTP/tree/fix/php-8-encoding-PSMEL-274), and confirm us whether it fixes the issue or not.

FYI: The malformed email is the conflict with the PHP Version, we added the compatibility with other PHP Versions, which is conflicting with yours.

If issue still persists feel free to inform us. 

Thanks

**Comment by DDougster** [comment]
Is that a full version of the Post-SMTP that will work with php 8.1? Do I replace the current version of the plugin with that?

**Comment by DDougster** [comment]
Installed it and here is the test email (junk) I received: (Let me know if you want me to send you a test email directly so you can examine the code)

MIME-Version: 1.0

Content-Type: multipart/alternative;

boundary="=_0677109238aa913172e48888ed564cad"

From: Monical's Pizza <[monicals@monicals.com](mailto:monicals@monicals.com)>

To: [DSDavis@monicals.com](mailto:DSDavis@monicals.com)

Message-Id: <[c41685124a5ed420e545d67fe67a67c1@monicals.biz](mailto:c41685124a5ed420e545d67fe67a67c1@monicals.biz)>

Subject: Postman SMTP Test ([www.monicals.biz](http://www.monicals.biz/))

Date: Fri, 10 Mar 2023 13:39:47 +0000


--=_0677109238aa913172e48888ed564cad

Content-Type: text/plain; charset=UTF-8

Content-Transfer-Encoding: quoted-printable



Hello!=0D=0DSent by Postman 2.4.2 - https://wordpress.org/plugins/post-s=

mtp/=0D=0D



--=_0677109238aa913172e48888ed564cad

Content-Type: text/html; charset=UTF-8

Content-Transfer-Encoding: quoted-printable



<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN " "http://w/=

ww.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">=0D<html xmlns=3D"http:=

//[www.w3.org/1999/xhtml](http://www.w3.org/1999/xhtml)">=0D<head>=0D<meta http-equiv=3D"Content-Type" c=

ontent=3D"text/html; charset=3Dutf-8" />=0D<style type=3D"text/css" medi=

a=3D"all">=0D.wporg-notification .im {=0D=09color: #888;=0D} /* undo a G=

Mail-inserted style */=0D</style>=0D</head>=0D<body class=3D"wporg-notif=

ication">=0D=09<div style=3D"background: #e8f6fe; font-family: &amp; quo=

t; Helvetica Neue&amp;quot; , Helvetica ,Arial,sans-serif; font-size: 14=

px; color: #666; text-align: center; margin: 0; padding: 0">=0D=09=09<ta=

ble border=3D"0" cellspacing=3D"0" cellpadding=3D"0" bgcolor=3D"#e8f6fe"=

=09style=3D"background: #e8f6fe; width: 100%;">=0D=09=09=09<tbody>=0D=09=

=09=09=09<tr>=0D=09=09=09=09=09<td>=0D=09=09=09=09=09=09<table border=3D=

"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"center" style=3D"paddin=

g: 0px; width: 100%;"">=0D=09=09=09=09=09=09=09<tbody>=0D=09=09=09=09=09=

=09=09=09<tr>=0D=09=09=09=09=09=09=09=09=09<td>=0D=09=09=09=09=09=09=09=

=09=09=09<div style=3D"max-width: 600px; height: 400px; margin: 0 auto;=

overflow: hidden;background-image:url('https://ps.w.org/postman-smtp/as=

sets/email/poofytoo.png');background-repeat: no-repeat;">=0D=09=09=09=09=

=09=09=09=09=09=09=09<div style=3D"margin:50px 0 0 300px; width:300px; f=

ont-size:2em;">Hello! - &#20320;&#22909; - Bonjour! - &#2344;&#2350;&#23=

60;&#2381;&#2340;&#2375; - =C2=A1Hola! - Ol&#225; - &#1055;&#1088;&#1080=

;&#1074;&#1077;&#1090;! - &#20170;&#26085;&#12399;</div>=0D=09=09=09=09=

=09=09=09=09=09=09=09<div style=3D"text-align:right;font-size: 1.4em; co=

lor:black;margin:150px 0 0 200px;">Sent by Postman 2.4.2=0D=09=09=09=09=

=09=09=09=09=09=09=09=09<br/>=0D=09=09=09=09=09=09=09=09=09=09=09</div>=

=0D=09=09=09=09=09=09=09=09=09=09</div>=0D=09=09=09=09=09=09=09=09=09</t=

d>=0D=09=09=09=09=09=09=09=09</tr>=0D=09=09=09=09=09=09=09</tbody>=0D=09=

=09=09=09=09=09</table>=0D=09=09=09=09=09=09<br><span style=3D"font-size=

:0.9em;color:#94c0dc;">Image source: <a style=3D"color:#94c0dc" href=3D"=

http://poofytoo.com/ ">poofytoo.com</a> - Used with permission</span>=0D=

=09=09=09=09=09</td>=0D=09=09=09=09</tr>=0D=09=09=09</tbody>=0D=09=09</t=

able>=0D</body>=0D</html>



--=_0677109238aa913172e48888ed564cad--

**Comment by DDougster** [comment]
Feel free to reach me directly:  dsdavis@monicals.com

Thanks ...
Doug

**Comment by smusmanobjects** [comment]
Hi,

Thanks for providing details, please share your Diagnostic Test here.
After that, start using this [build](https://github.com/wpexpertsio/Post-SMTP/files/10953624/post-smtp.2.4.4.zip).

Thanks😀

**Comment by DDougster** [comment]
Due to the need to keep email working, I had already rolled back to version 2.4.3. In the future, I will share the test results here when issues arise. However, on a solid note, that version 2.4.4 worked perfectly in our system. For future reference, I will also show the working diagnostics for our system.

**Comment by DDougster** [comment]
Here is the most recent one:

Mailer: postsmtp
HostName: monicals.biz
cURL Version: 7.88.1
OpenSSL Version: OpenSSL/1.1.1t
OS: Linux web.monicalspizza.com 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64
PHP: Linux 8.1.16 C
PHP Dependencies: iconv=Yes, spl_autoload=Yes, openssl=Yes, sockets=Yes, allow_url_fopen=No, mcrypt=No, zlib_encode=Yes
WordPress: 6.1.1 en_US UTF-8
WordPress Theme: Monicals Pizza
WordPress Plugins: Post SMTP, Gravity Forms, Advanced Custom Fields PRO, Classic Editor, Anti-Spam by CleanTalk, Yoast Duplicate Post, Enable Media Replace, EWD Premium Helper, Gravity Forms + Custom Post Types, WPCode Lite, jQuery Manager for WordPress, Prevent XSS Vulnerability, VarkTech Pricing Deals for WooCommerce, VarkTech Pricing Deals PRO for WooCommerce, Regenerate Thumbnails, Stop User Enumeration, The Events Calendar, Ultimate FAQ - WordPress FAQ and Accordion Plugin, Woo Manage Fraud Orders, WooCommerce Checkout Manager, WooCommerce Customer/Order/Coupon Export, WooCommerce Clover (formerly First Data Payeezy Gateway), PDF Invoices & Packing Slips for WooCommerce, WooCommerce PDF Invoices & Packing Slips Professional, WooCommerce Product Archive Customiser, WooCommerce Wholesale Lead Capture, WooCommerce Wholesale Prices, WooCommerce, WP File Manager
WordPress wp_mail Owner: /home/webrat/public_html/wp-content/plugins/post-smtp/Postman/PostmanWpMailBinder.php
WordPress wp_mail Filter(s): wp_staticize_emoji_for_email, WPO\WC\PDF_Invoices\Main->set_phpmailer_validator, PostsmtpMailer->get_mail_args
WordPress phpmailer_init Action(s): WC_Email_New_Order->handle_multipart, WC_Email_Cancelled_Order->handle_multipart, WC_Email_Failed_Order->handle_multipart, WC_Email_Customer_On_Hold_Order->handle_multipart, WC_Email_Customer_Processing_Order->handle_multipart, WC_Email_Customer_Completed_Order->handle_multipart, WC_Email_Customer_Refunded_Order->handle_multipart, WC_Email_Customer_Invoice->handle_multipart, WC_Email_Customer_Note->handle_multipart, WC_Email_Customer_Reset_Password->handle_multipart, WC_Email_Customer_New_Account->handle_multipart, WC_Email_Customer_Credit_Note->handle_multipart, WC_Email_Customer_Credit_Note->handle_multipart, PostsmtpMailer->phpmailer_smtp_init
Postman: 2.4.4
Postman Sender Domain (Envelope|Message): monicals.com | monicals.com
Postman Prevent Message Sender Override (Email|Name): No | No
Postman Active Transport: SMTP (smtp:tls:crammd5://kerio10.bigmountainmail.com:587)
Postman Active Transport Status (Ready|Connected): Yes | Yes
Postman Deliveries (Success|Fail): 222 | 9

**Comment by smusmanobjects** [comment]
Hi there,

I hope you are doing well😀.
Update plugin to latest version 2.4.5, we have fixed the issues.

Thanks

**Comment by DDougster** [comment]
Yes, I saw that and updated then tested.  All is good now. Feel free to let me know when you have to test another new release.

Douglas S. Davis
Information Systems Coordinator

 Monical Pizza Corporation
 815/929-2074 - Office
815/644-4863 - Emergency

 This communication may contain proprietary and confidential information for the sole use of the intended recipient.
If you are not the intended recipient, please note that any other dissemination, distribution, use or copying of this
communication is strictly prohibited. Anyone who receives this message in error should notify the sender immediately
by telephone or by return eMail and delete it from their computer.

**Comment by smusmanobjects** [comment]
👋 Hey there!

Yes 

📧 Exciting news! We've completely revamped our email logging system and released a beta that makes it faster!

🚀 Check out the beta [here](https://github.com/wpexpertsio/Post-SMTP/archive/refs/heads/beta/custom-logs-table.zip).

👷‍♀️ Make sure to try it out on your staging website first and report any bugs 🐛 to us!

🔧 Need help configuring? Here's a helpful [guide](https://www.awesomescreenshot.com/video/15413807?key=d1b92a96b5112cf580e9c80d073fdb5b)

❓ Any questions? Don't hesitate to ask! Thanks for your support! 😄

Thanks

**Comment by smusmanobjects** [comment]
Hi, 

I hope you are doing well.
Did you try out the beta?

Thanks

**Comment by smusmanobjects** [comment]
Hi ✋,

I hope you are doing well,
Thanks for the update,
Did you like new logging system?

Thanks
